package com.example.polivmi1.vyngproject.models;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Uid;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Video {

    public static int nextID = 0;

    @Id
    long id;
    private String icon;
    private String video;
    @Uid(4625621373166283263L)
    private String key;
    private int likes;

    public Video(String key, String icon, String video) {
        this.icon = icon;
        this.video = video;
        this.key = key;
    }


    @Generated(307294836)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Video(long id, String icon, String video, String key, int likes) {
        this.id = id;
        this.icon = icon;
        this.video = video;
        this.key = key;
        this.likes = likes;
    }


    @Generated(237528154)
    public Video() {
    }


    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public String getVideo() {
        return video;
    }

    public void setVideo(String video) {
        this.video = video;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public void assignID() {
        id = nextID;
        nextID++;
    }

    public long getID() {
        return id;
    }


    public int getLikes() {
        return likes;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }

    public void increaseLikes() {
        likes++;
    }

    public void decreaseLikes() {
        likes--;
    }
}